version: '3.8'

services:

  frontend:
    build: kiosk_upload/
    expose:
      - '8000'
    volumes:
      - static:/opt/app/static/
      - media:/opt/app/media/
    env_file:
      - .env
    command: uwsgi --strict --ini uwsgi.ini

  rabbitmq:
    image: rabbitmq:3.11.8-management-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "5672" ]
        interval: 10s
        timeout: 10s
        retries: 5
    
  postgres:
    image: postgres:15.1-alpine3.17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres-init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    env_file:
      - .env
  
  nginx:
    image: nginx:1.22.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/var/www/static/:ro
      - media:/var/www/media/:ro
    depends_on:
      - notify_admin
    ports:
      - "80:80"

volumes:
  media:
  static:
  postgres_data:

networks:
  default:
    name: kiosk_banners
  