# Generated by Django 4.1.5 on 2023-02-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiosk',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosks', to='kiosk_front.cinema', verbose_name='Cinema'),
        ),
    ]
